/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canonodesign;

import java.awt.Color;
import INTERNALPAGES.*;
import INTERNALPAGES.DashboardPage;
/**
 *
 * @author canono
 */
public class dashboards extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboards() {
        initComponents();
        
         DashboardPage dbp = new DashboardPage();
        maindesktop.add(dbp).setVisible(true);
    }
 Color navcolor = new Color(0,153,255);
 Color headcolor = new Color(0,204,204);
 Color bodycolor = new Color(204,255,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        DASH = new javax.swing.JPanel();
        DASHBOARD = new javax.swing.JLabel();
        studentpage = new javax.swing.JPanel();
        USER = new javax.swing.JLabel();
        account = new javax.swing.JPanel();
        USER1 = new javax.swing.JLabel();
        userpage = new javax.swing.JPanel();
        USER2 = new javax.swing.JLabel();
        department = new javax.swing.JPanel();
        USER3 = new javax.swing.JLabel();
        enrollees = new javax.swing.JPanel();
        USER4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        maindesktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        navbar.setBackground(new java.awt.Color(0, 153, 255));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DASH.setBackground(new java.awt.Color(0, 153, 255));
        DASH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DASHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DASHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DASHMouseExited(evt);
            }
        });
        DASH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DASHBOARD.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        DASHBOARD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DASHBOARD.setText("DASHBOARD");
        DASH.add(DASHBOARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        navbar.add(DASH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, 30));

        studentpage.setBackground(new java.awt.Color(0, 153, 255));
        studentpage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentpageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentpageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentpageMouseExited(evt);
            }
        });
        studentpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        USER.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        USER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USER.setText("STUDENTS");
        studentpage.add(USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        navbar.add(studentpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 30));

        account.setBackground(new java.awt.Color(0, 153, 255));
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountMouseExited(evt);
            }
        });
        account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        USER1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        USER1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USER1.setText("ACCOUNT");
        account.add(USER1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        navbar.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 120, 30));

        userpage.setBackground(new java.awt.Color(0, 153, 255));
        userpage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userpageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userpageMouseExited(evt);
            }
        });
        userpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        USER2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        USER2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USER2.setText("USERS");
        userpage.add(USER2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        navbar.add(userpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, 30));

        department.setBackground(new java.awt.Color(0, 153, 255));
        department.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                departmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                departmentMouseExited(evt);
            }
        });
        department.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        USER3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        USER3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USER3.setText("DEPARTMENT");
        department.add(USER3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        navbar.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 120, 30));

        enrollees.setBackground(new java.awt.Color(0, 153, 255));
        enrollees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enrolleesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enrolleesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enrolleesMouseExited(evt);
            }
        });
        enrollees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        USER4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        USER4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USER4.setText("ENROLLEES");
        enrollees.add(USER4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        navbar.add(enrollees, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsfolder/LOGO (1) (1).png"))); // NOI18N
        navbar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 100));

        jPanel1.add(navbar);
        navbar.setBounds(0, 0, 120, 380);

        header.setBackground(new java.awt.Color(204, 255, 255));
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headerMouseClicked(evt);
            }
        });

        exit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        minimize.setText("-");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(462, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addGap(18, 18, 18))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        jPanel1.add(header);
        header.setBounds(120, 0, 530, 40);

        maindesktop.setBackground(new java.awt.Color(0, 204, 204));
        maindesktop.setPreferredSize(new java.awt.Dimension(547, 376));

        javax.swing.GroupLayout maindesktopLayout = new javax.swing.GroupLayout(maindesktop);
        maindesktop.setLayout(maindesktopLayout);
        maindesktopLayout.setHorizontalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        maindesktopLayout.setVerticalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel1.add(maindesktop);
        maindesktop.setBounds(120, 40, 530, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DASHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DASHMouseEntered
        DASH.setBackground(bodycolor);
    }//GEN-LAST:event_DASHMouseEntered

    private void DASHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DASHMouseExited
        DASH.setBackground(navcolor);
    }//GEN-LAST:event_DASHMouseExited

    private void studentpageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentpageMouseEntered
       studentpage.setBackground(bodycolor);
    }//GEN-LAST:event_studentpageMouseEntered

    private void studentpageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentpageMouseExited
       studentpage.setBackground(navcolor);
    }//GEN-LAST:event_studentpageMouseExited

    private void accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseEntered
        account.setBackground(bodycolor);
    }//GEN-LAST:event_accountMouseEntered

    private void accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseExited
        account.setBackground(navcolor);
    }//GEN-LAST:event_accountMouseExited

    private void studentpageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentpageMouseClicked
        studentPage up = new studentPage();
        maindesktop.add(up).setVisible(true);
    }//GEN-LAST:event_studentpageMouseClicked

    private void headerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseClicked
   

    }//GEN-LAST:event_headerMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
            
System.exit(0);

    }//GEN-LAST:event_exitMouseClicked

    private void DASHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DASHMouseClicked
        DashboardPage dbp = new DashboardPage();
        maindesktop.add(dbp).setVisible(true);
    }//GEN-LAST:event_DASHMouseClicked

    private void userpageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpageMouseEntered
       userpage.setBackground(bodycolor);
    }//GEN-LAST:event_userpageMouseEntered

    private void userpageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpageMouseExited
          userpage.setBackground(navcolor);
    }//GEN-LAST:event_userpageMouseExited

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
         settingsPage set = new  settingsPage();
        maindesktop.add(set).setVisible(true);
    }//GEN-LAST:event_accountMouseClicked

    private void userpageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpageMouseClicked
      userPage up = new  userPage();
        maindesktop.add(up).setVisible(true);
    }//GEN-LAST:event_userpageMouseClicked

    private void departmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentMouseClicked
        departmentPage up = new   departmentPage();
        maindesktop.add(up).setVisible(true);
    }//GEN-LAST:event_departmentMouseClicked

    private void departmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentMouseEntered
      department.setBackground(bodycolor);
    }//GEN-LAST:event_departmentMouseEntered

    private void departmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentMouseExited
         department.setBackground(navcolor);
    }//GEN-LAST:event_departmentMouseExited

    private void enrolleesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrolleesMouseClicked
        enrollees up = new   enrollees();
        maindesktop.add(up).setVisible(true);
    }//GEN-LAST:event_enrolleesMouseClicked

    private void enrolleesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrolleesMouseEntered
       enrollees.setBackground(bodycolor);
    }//GEN-LAST:event_enrolleesMouseEntered

    private void enrolleesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrolleesMouseExited
        enrollees.setBackground(navcolor);
    }//GEN-LAST:event_enrolleesMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DASH;
    private javax.swing.JLabel DASHBOARD;
    private javax.swing.JLabel USER;
    private javax.swing.JLabel USER1;
    private javax.swing.JLabel USER2;
    private javax.swing.JLabel USER3;
    private javax.swing.JLabel USER4;
    private javax.swing.JPanel account;
    private javax.swing.JPanel department;
    private javax.swing.JPanel enrollees;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JDesktopPane maindesktop;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel studentpage;
    private javax.swing.JPanel userpage;
    // End of variables declaration//GEN-END:variables
}
